# Effectuer des comparaisons et Sélectionner des éléments

In [2]:
import numpy as np

world_alcohol = np.genfromtxt("../data.csv", 
                              delimiter=",", 
                              dtype="U75",
                              skip_header=1
                             )
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Comparaisonsde Vecteur

In [3]:
vector = np.array([5, 10, 15, 20])

In [4]:
vector == 10

array([False,  True, False, False])

## Comparaison de Matrice

In [5]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [6]:
matrix == 5

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

### Cas Pratique

In [7]:
countries = world_alcohol[:,2]
countries_canada = countries == "Canada"
countries_canada

array([False, False, False, ..., False, False, False])

In [8]:
years = world_alcohol[:,0]
years_1984 = years == "1984"
years_1984

array([False, False, False, ..., False, False, False])

### Sélectionner des éléments

In [9]:
vector = np.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[10]


In [10]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25,:])

[[20 25 30]]


In [12]:
country_is_algeria = (world_alcohol[:,2] == "Algeria")
print(world_alcohol[country_is_algeria,:])

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [13]:
years_is_1984 = (world_alcohol[:,0] == "1984")
print(world_alcohol[years_is_1984])
print(world_alcohol[years_is_1984])

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]
[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


### Effectuer des comparaisons avec plusieurs conditions

In [14]:
vector

array([ 5, 10, 15, 20])

In [15]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [16]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


- Sélectioner les lignes dont le pays est "Algeria" et l'année est "1986":

    - Créer cette double comparaison et assigner le résultat à la variable is_algeria_and_1986.
    - Utiliser is_algeria_and_1986 pour sélectionner les lignes correspondantes dans le tableau world_alcohol.
    - Assigner le résultat à la variable rows_with_algeria_and_1986.
    - Afficher le résultat.

In [21]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986,:]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]
