# Remplacer des valeurs dans un tableau Numpy

In [13]:
import numpy as np
world_alcohol = np.genfromtxt("../data.csv", 
                              delimiter=",", 
                              dtype="U75",
                              skip_header=1
                             )
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [14]:
vector = np.array([5, 10, 15, 20])

In [15]:
vector

array([ 5, 10, 15, 20])

In [16]:
equal_to_ten_of_five = (vector == 10) | (vector == 5)
print(equal_to_ten_of_five)

[ True  True False False]


In [17]:
vector[equal_to_ten_of_five] = 50
print(vector)

[50 50 15 20]


In [18]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
second_column_25 = matrix[:,1] == 25
print(second_column_25)

[False  True False]


In [21]:
matrix[second_column_25,1] = 10
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


- Créer un tableau numpy world_alcohol_2 égal world_alcohol pour le dupliquer sous un autre nom.
- Remplacer toutes les années "1986" de la première colonne de world_alcohol_2 par "2018".
- Remplacer tous les alcools "Wine" de la 4e colonne de world_alcohol_2 par "Beer".

In [22]:
world_alcohol_2 = world_alcohol
first_column_1986 = (world_alcohol_2[:,0] == "1986")
world_alcohol_2[first_column_1986,0] = "2018"
fourth_column_wine = world_alcohol_2[:,3] == "Wine"
world_alcohol_2[fourth_column_wine,3] = "Beer"
print(world_alcohol_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


## Remplacer les chaines de caractères vides
- Comparer tous les éléments de la 5e colonne de world_alcohol avec la chaine de caractères vides c'est à dire ''. Assigner le résultat à la variable is_value_empty.
- Sélectionner toutes les valeurs de la 5e colonne de world_alcohol pour lesquelles is_value_empty est égal à True et enfin les remplacer par la chaine de caractères '0'.

In [23]:
is_value_empty = (world_alcohol[:,4] == '')
world_alcohol[is_value_empty,4] = '0'