# Convertir des types de données

In [1]:
import numpy as np
world_alcohol = np.genfromtxt("../data.csv", 
                              delimiter=",", 
                              dtype="U75",
                              skip_header=1
                             )
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [2]:
vector = np.array(["1", "2", "3"])

In [3]:
vector = vector.astype(float)

In [4]:
vector

array([1., 2., 3.])

In [5]:
is_value_empty = world_alcohol[:,4] == ''
world_alcohol[is_value_empty,4] = '0'

## Convertir des types de données

- Extraire la 5e colonne de world_alcohol et assigner le résultat à la variable alcohol_consumption.
- Utiliser la méthode astype() pour convertir alcohol_consumption en décimal (float).

In [6]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)

In [7]:
alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

## Réaliser des calculs mathématiques avec Numpy

In [8]:
vector = np.array([5, 10, 15, 20])

In [9]:
vector.sum()

50

In [10]:
vector.mean()

12.5

In [11]:
vector.max()

20

In [12]:
vector.min()

5

In [13]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [14]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [16]:
matrix.sum(axis=0)

array([60, 75, 90])

## Réaliser des calculs mathématiques avec Numpy

- Utiliser la méthode sum() pour calculer la somme des valeurs de alcohol_consumption. Assigner le résultat à la variable total_alcohol.
- Utiliser la méthode mean() pour calculer la moyenne des valeurs de alcohol_consumption. Assigner le résultat à la variable average_alcohol.
- Afficher les résultats.

In [17]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()

In [18]:
print(total_alcohol)

3908.96


In [19]:
print(average_alcohol)

1.2001719373656738


## Calculer la consommation totale annuelle par habitant pour un pays donné
- Créer une matrice qu'on nommera canada_1986 qui contient toutes les lignes de world_alcohol correspondant à l'année "1986" et au pays "Canada".
- Extraire la 5e colonne de canada_1986, remplacer toute chaine de caractères vides ('') par '0' et convertir la colonne en décimal (float). Assigner le résultat à la variable canada_alcohol.
- Calculer la somme de canada_alcohol. Assigner le résultat à la variable total_canadian_drinking.
- Afficher le résultat.

In [20]:
canada_1986 = world_alcohol[(world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Canada")]
canada_alcohol = canada_1986[:,4]
canada_alcohol = canada_alcohol.astype(float)
total_canadian_drinking = canada_alcohol.sum()

In [21]:
print(canada_1986)

[['1986' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]


In [22]:
print(canada_alcohol)

[0.   3.11 4.87 1.33]


In [23]:
print(total_canadian_drinking)

9.31


## Calculer la consommation pour chaque pays
- Tout d'abord, on crée un dictionnaire vide qui va contenir tous les pays et leurs consommations d'alcool associées, on le nommera totals.
- Sélectionner ensuite les lignes de world_alcohol correspondant à l'année donnée, disons 1989. Assigner le résultat à la variable year.
- Sélectionner dans une liste qu'on nommera countries tous les pays.
- Parcourir tous les pays de la liste à l'aide d'une boucle. Pour chaque pays:
    - Sélectionner les lignes de year correspondant à ce pays
    - Assigner le résultat à la variable country_consumption
    - Extraire la 5e colonne de country_consumption
    - Remplacer toute chaine de caractères vide dans cette colonne par 0
    - Convertir la colonne en décimal (float)
    - Calculer la somme de la colonne
    - Ajouter la somme au dictionnaire totals, avec comme clé le nom du pays et en valeur cette somme.
- Afficher le dictionnaire totals.

In [25]:
totals = {}
is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]
countries = world_alcohol[:,2]

for country in countries:
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ""
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()

print(totals)

{'Viet Nam': 0.16, 'Uruguay': 7.4399999999999995, "Cte d'Ivoire": 2.2, 'Colombia': 6.960000000000001, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.3999999999999995, 'Seychelles': 3.3000000000000003, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.10999999999999999, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.899999999999999, 'Sierra Leone': 4.380000000000001, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42000000000000004, 'Sweden': 7.47, 'Qatar': 1.4500000000000002, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.009999999999998, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92, 'Trinidad and 

## Trouver le pays qui consomme le plus d'alcool
- Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
- Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
- Parcourir chaque pays du dictionnaire totals:
    - Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable highest_value et assigner la clé correspondante (nom du pays) à la variable highest_key.
- Afficher le pays qui consomme le plus d'alcool (variable highest_key)

In [26]:
highest_value = 0
highest_key = None

for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country
        
print(highest_key)

Hungary
