# Affichage et Extraction de données

### Affichage de données

In [4]:
import numpy as np

world_alcohol = np.genfromtxt("../data.csv", 
                              delimiter=",", 
                              dtype="U75", 
                              skip_header=1
                             )
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Extraire une valeur depuis un tableau Numpy

In [5]:
vector = np.array([5, 10, 15, 20])
print(vector[0])

5


In [6]:
list_of_lists = [[5, 10, 15], [20, 25, 30]]

In [7]:
first_row = list_of_lists[0]

In [8]:
first_row[2]

15

In [9]:
list_of_lists[0][2]

15

In [10]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])

In [12]:
matrix[1,2]

30

In [16]:
ivoire_1985 = world_alcohol[2,4]
print('ivoire_1985 ---> ',ivoire_1985)

ivoire_1985 --->  1.62


In [17]:
second_country = world_alcohol[1,2]
print('second_country ----> ',second_country)

second_country ---->  Uruguay


### Extraire un vecteur depuis un tableau Numpy

In [19]:
vector = np.array([5, 10, 15, 20])

In [20]:
vector[0:3]

array([ 5, 10, 15])

In [21]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [22]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
matrix[:,1]

array([10, 25, 40])

In [25]:
matrix[2,:]

array([35, 40, 45])

In [28]:
matrix[1:3,1]

array([25, 40])

In [31]:
countries = world_alcohol[:,2]
countries

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [32]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75')

### Extraire un tableau de valeurs depuis un tableau Numpy

In [33]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
matrix[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [35]:
matrix[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [36]:
matrix[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [37]:
first_two_columns = world_alcohol[:,0:2]
print(first_two_columns)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [41]:
first_ten_years = world_alcohol[0:10,0]
print(first_ten_years)

['1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986' '1984']


In [42]:
first_ten_rows = world_alcohol[0:10,:]
print(first_ten_rows)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [43]:
first_twenty_regions = world_alcohol[0:20,1:3]
print(first_twenty_regions)

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]
