# Découverte de Numpy

### Les tableaux avec numpy

In [1]:
import numpy as np
vector = np.array([3, 4, 17, 65])

In [4]:
print(vector)

[ 3  4 17 65]


In [5]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [6]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


#### taille d'un vecteur

In [9]:
vector_shape = vector.shape
print(vector_shape)

(4,)


#### taille d'une matrice

In [10]:
matrix_shape = matrix.shape
print(matrix_shape)

(3, 3)
